import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { migrateLegacyConfig, migrateLegacySession } from '../src/compatibility.ts';
import { assertSessionCompliance } from '../apps/simulator/src/compliance.ts';
const original = JSON.parse(readFileSync(new URL('./fixtures/legacy-session.json', import.meta.url), 'utf8'));
const before = JSON.stringify(original);
const migrated = migrateLegacySession(original);
assert.equal(JSON.stringify(original), before, 'migration must not mutate input');
assert.equal(migrated.data.stateId, 'state');
assert.notEqual(migrated.data.stateHash, original.psiHash, 'default ID has an explicitly new hash');
assert.deepEqual(migrated.data.currentState.latent, original.psi.latent);
assert.equal(migrated.data.frameCount, original.frameCount);
assertSessionCompliance(migrated.data);
const bad = structuredClone(original); bad.frames[5].rho += 0.01;
assert.throws(() => migrateLegacySession(bad), /compliance/);
const badHash = structuredClone(original); badHash.hashes[3] = '00000000';
assert.throws(() => migrateLegacySession(badHash), /compliance/);
assert.throws(() => migrateLegacySession({ ...original, schemaVersion: 'unknown' }), /Only exports/);
assert.throws(() => migrateLegacyConfig({ gammaScale: NaN }));
assert.throws(() => migrateLegacyConfig({ newUnknownKey: 1 }));
assert.throws(() => migrateLegacyConfig({ tau: 0.7, projectionThreshold: 0.8 }), /Ambiguous/);
assert.deepEqual(migrateLegacyConfig({ reflexRate: 0.2, ablations: { omega: false } }), { smoothingRate: 0.2, mechanisms: { noise: false } });
console.log('PASS: legacy configuration and trace migration, immutable input, numerical preservation, and tamper rejection.');
