/**
 * SINGLE-TRAJECTORY-1 runner.
 *
 *   node --experimental-strip-types scripts/st1-run.mjs parity
 *   node --experimental-strip-types scripts/st1-run.mjs train-val
 *   node --experimental-strip-types scripts/st1-run.mjs test
 *
 * train-val never generates test seeds.
 * test refuses to start unless the lock manifest matches the frozen files.
 * Every command rejects seeds 1040-1059.
 */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  SPLITS,
  assertNotProhibited,
  assertParity,
  encodeVec,
  simulateSplit,
} from "./st1-adapter.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const FROZEN = [
  "docs/SINGLE_TRAJECTORY_1.md",
  "scripts/st1-adapter.mjs",
  "scripts/st1-analysis.py",
  "scripts/st1-run.mjs",
  "src/engine.ts",
];
const VALIDATION_JSON = "docs/st1-validation.json";
const VALIDATION_MD = "docs/st1-validation.md";
const LOCK_JSON = "docs/st1-lock.json";
const RESULT_JSON = "docs/st1-result.json";
const RESULT_MD = "docs/SINGLE_TRAJECTORY_1_RESULT.md";

function fail(message) {
  throw new Error(`st1: ${message}`);
}

function sha256(rel) {
  return createHash("sha256").update(readFileSync(path.join(root, rel))).digest("hex");
}

function fileHashes() {
  const out = {};
  for (const rel of FROZEN) out[rel] = sha256(rel);
  return out;
}

function writeAtomic(rel, text) {
  const dest = path.join(root, rel);
  const tmp = `${dest}.tmp`;
  writeFileSync(tmp, text);
  renameSync(tmp, dest);
}

function python(mode, payload) {
  const res = spawnSync("python3", [path.join(root, "scripts/st1-analysis.py"), mode], {
    cwd: root,
    input: payload === undefined ? "" : JSON.stringify(payload),
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  if (res.status !== 0) {
    process.stderr.write(res.stderr || "");
    process.stderr.write(res.stdout || "");
    fail(`python ${mode} exited ${res.status}`);
  }
  if (mode === "--self-check") return res.stdout.trim();
  return JSON.parse(res.stdout);
}

function versions() {
  const res = spawnSync("python3", ["-c", "import sys,numpy; print(sys.version.split()[0]); print(numpy.__version__)"], { encoding: "utf8" });
  if (res.status !== 0) fail("could not read python versions");
  const [pythonVersion, numpy] = res.stdout.trim().split("\n");
  return { python: pythonVersion, numpy, node: process.version };
}

function packEpisodes(episodes) {
  return episodes.map((ep) => {
    const integrator = {};
    for (const rate of Object.keys(ep.integrator)) integrator[rate] = encodeVec(ep.integrator[rate]);
    return {
      seed: ep.seed,
      b1: ep.b1,
      b2: ep.b2,
      y: ep.y,
      initial: encodeVec(ep.initial),
      engine: encodeVec(ep.engine),
      final_input: encodeVec(ep.finalInput),
      integrator,
    };
  });
}

function assertSplit(episodes, name) {
  const expected = SPLITS[name];
  const seeds = [];
  for (const ep of episodes) {
    assertNotProhibited(ep.seed);
    if (!seeds.length || seeds[seeds.length - 1] !== ep.seed) seeds.push(ep.seed);
    if (name !== "test" && SPLITS.test.includes(ep.seed)) fail(`test seed ${ep.seed} reached ${name}`);
  }
  if (seeds.length !== expected.length || seeds.some((seed, i) => seed !== expected[i])) {
    fail(`split ${name} does not match the frozen allowlist`);
  }
  if (episodes.length !== expected.length * 4) fail(`split ${name} is not complete blocks`);
}

function exactHalf(row) {
  return row.train_correct * 2 === row.train_total && row.val_correct * 2 === row.val_total;
}

function withoutCoef(row) {
  const copy = { ...row };
  delete copy.weights_hex;
  delete copy.intercept_hex;
  delete copy.mean_hex;
  delete copy.sd_hex;
  delete copy.B_hex;
  delete copy.c_hex;
  return copy;
}

function fmt(n) {
  return Number(n).toFixed(6);
}

function rate(correct, total) {
  return `${correct}/${total} (${fmt(correct / total)})`;
}

function gridTable(rows) {
  const lines = [
    "| arm | a | lambda | validation | train | val log loss | converged |",
    "| --- | --- | ---: | --- | --- | ---: | --- |",
  ];
  for (const row of rows) {
    lines.push(`| ${row.arm} | ${row.a} | ${row.lambda} | ${row.val_correct}/${row.val_total} | ${row.train_correct}/${row.train_total} | ${fmt(row.val_nll)} | ${row.converged ? "yes" : "no"} |`);
  }
  return lines.join("\n");
}

function validationMarkdown(report) {
  const lines = [
    "# SINGLE-TRAJECTORY-1 validation",
    "",
    `Status: ${report.status}.`,
    "Test trajectories were not generated by this command.",
    "",
    "The closed baseline files were not read or modified.",
    "",
    "## Selection",
    "",
  ];
  if (report.selected_engine) {
    lines.push(`Corrected engine: lambda=${report.selected_engine.lambda}, validation ${rate(report.selected_engine.val_correct, report.selected_engine.val_total)}, log loss ${fmt(report.selected_engine.val_nll)}.`);
    lines.push(`Corrected integrator: a=${report.selected_integrator.a}, lambda=${report.selected_integrator.lambda}, validation ${rate(report.selected_integrator.val_correct, report.selected_integrator.val_total)}, log loss ${fmt(report.selected_integrator.val_nll)}.`);
    lines.push("");
    lines.push(`Lambda edge: engine ${report.edges.engine.lambda_edge ? "yes" : "no"}, integrator ${report.edges.integrator.lambda_edge ? "yes" : "no"}.`);
    lines.push(`Rate edge: ${report.edges.integrator.rate_edge ? "yes" : "no"}. The grids were not extended.`);
  } else {
    lines.push("No model was selected.");
  }
  lines.push("");
  lines.push("## Leakage controls");
  lines.push("");
  lines.push("Initial-only and final-input-only must be exactly half on train and validation.");
  lines.push("");
  lines.push(gridTable(report.control_rows.initial));
  lines.push("");
  lines.push(gridTable(report.control_rows.final_input));
  lines.push("");
  lines.push("## Corrected engine grid");
  lines.push("");
  lines.push(gridTable(report.engine_rows));
  lines.push("");
  lines.push("## Corrected integrator grid");
  lines.push("");
  lines.push(gridTable(report.integrator_rows));
  lines.push("");
  lines.push("## Raw and delta controls");
  lines.push("");
  lines.push(gridTable(report.control_rows.raw));
  lines.push("");
  lines.push(gridTable(report.control_rows.delta));
  lines.push("");
  if (report.failures.length) {
    lines.push("## Fit failures");
    lines.push("");
    for (const item of report.failures) lines.push(`- ${item}`);
    lines.push("");
  }
  lines.push("This is the validation inspection. It is not a test result.");
  lines.push("");
  return lines.join("\n");
}

function runParity() {
  const check = python("--self-check");
  if (!check.startsWith("self-check ok")) fail(check);
  assertParity();
  if (existsSync(path.join(root, RESULT_JSON))) fail("parity must not be confused with a finished test, but the result file is present");
  console.log(check);
  console.log("parity ok");
}

function runTrainVal() {
  if (existsSync(path.join(root, RESULT_JSON))) fail("test result already exists; refusing to refit");
  const check = python("--self-check");
  if (!check.startsWith("self-check ok")) fail(check);
  assertParity();
  const train = simulateSplit("train");
  const validation = simulateSplit("validation");
  assertSplit(train, "train");
  assertSplit(validation, "validation");
  const selected = python("--select", {
    train: packEpisodes(train),
    validation: packEpisodes(validation),
  });
  const leakageOk = selected.control_rows.initial.every(exactHalf) && selected.control_rows.final_input.every(exactHalf);
  let status = "LOCKED_FOR_TEST";
  let proceed = true;
  if (selected.failures.length) {
    status = "INVALID_FIT";
    proceed = false;
  } else if (!leakageOk || !selected.selected_engine || !selected.selected_integrator) {
    status = "INVALID_LEAKAGE";
    proceed = false;
  } else if (selected.selected_integrator.val_correct / selected.selected_integrator.val_total > 0.85) {
    status = "TASK_UNINFORMATIVE";
    proceed = false;
  }
  const report = {
    experiment: "SINGLE-TRAJECTORY-1",
    status,
    proceed,
    engine_reference: "917c3e9df6a313474b22b28ff6574435313fc808",
    test_generated: false,
    leakage_ok: leakageOk,
    failures: selected.failures,
    edges: selected.edges,
    selected_engine: selected.selected_engine ? withoutCoef(selected.selected_engine) : null,
    selected_integrator: selected.selected_integrator ? withoutCoef(selected.selected_integrator) : null,
    selected_controls: selected.selected_controls ? {
      raw: withoutCoef(selected.selected_controls.raw),
      delta: withoutCoef(selected.selected_controls.delta),
      initial: withoutCoef(selected.selected_controls.initial),
      final_input: withoutCoef(selected.selected_controls.final_input),
    } : null,
    engine_rows: selected.engine_rows,
    integrator_rows: selected.integrator_rows,
    control_rows: selected.control_rows,
  };
  writeAtomic(VALIDATION_JSON, `${JSON.stringify(report, null, 2)}\n`);
  writeAtomic(VALIDATION_MD, validationMarkdown(report));
  const lock = {
    experiment: "SINGLE-TRAJECTORY-1",
    status,
    proceed,
    engine_reference: "917c3e9df6a313474b22b28ff6574435313fc808",
    versions: versions(),
    files: fileHashes(),
    validation_sha256: sha256(VALIDATION_JSON),
    seeds: SPLITS,
    solver: "newton-armijo-40-1e-8-c-1e-4",
    selected_engine: selected.selected_engine,
    selected_integrator: selected.selected_integrator,
    selected_controls: selected.selected_controls,
    edges: selected.edges,
    leakage_ok: leakageOk,
    failures: selected.failures,
  };
  writeAtomic(LOCK_JSON, `${JSON.stringify(lock, null, 2)}\n`);
  console.log(`train-val status ${status}`);
  if (selected.selected_integrator) {
    console.log(`integrator validation ${selected.selected_integrator.val_correct}/${selected.selected_integrator.val_total} a=${selected.selected_integrator.a} lambda=${selected.selected_integrator.lambda}`);
  }
  if (selected.selected_engine) {
    console.log(`engine validation ${selected.selected_engine.val_correct}/${selected.selected_engine.val_total} lambda=${selected.selected_engine.lambda}`);
  }
  if (!proceed) console.log("test generation was not authorized");
}

function verifyLock(lock) {
  if (!lock || lock.proceed !== true || lock.status !== "LOCKED_FOR_TEST") fail("lock does not authorize test");
  const files = fileHashes();
  for (const rel of FROZEN) {
    if (lock.files[rel] !== files[rel]) fail(`frozen file changed after lock: ${rel}`);
  }
  if (lock.validation_sha256 !== sha256(VALIDATION_JSON)) fail("validation report changed after lock");
  const now = versions();
  if (now.python !== lock.versions.python || now.numpy !== lock.versions.numpy || now.node !== lock.versions.node) {
    fail("dependency versions changed after lock");
  }
  for (const seed of SPLITS.test) assertNotProhibited(seed);
  for (const seed of [...SPLITS.train, ...SPLITS.validation, ...SPLITS.test]) assertNotProhibited(seed);
}

function intervalLine(name, interval) {
  return `${name}: [${fmt(interval.low)}, ${fmt(interval.high)}], width ${fmt(interval.width)}`;
}

function readings(score) {
  const eng = score.intervals.engine;
  const raw = score.intervals.raw;
  const delta = score.intervals.delta;
  const clears = (interval) => interval.low > 0.5;
  const corrected = score.summaries.engine.accuracy;
  const lines = [];
  if (score.verdict.benefit && score.summaries.raw.accuracy < corrected && score.summaries.delta.accuracy < corrected) {
    lines.push("Corrected engine succeeded while raw and delta lagged. That is consistent with nuisance masking. Independent confirmation is needed.");
  }
  if (clears(eng) && !score.verdict.benefit) {
    lines.push("The corrected engine cleared chance but not the conjunctive success rule. Usable signal is shown. Comparative benefit is not established.");
  }
  if (!clears(eng) && !clears(raw) && !clears(delta)) {
    lines.push("No engine representation cleared chance. This task and these readouts did not demonstrate usable signal. Do not conclude that all class information is absent.");
  }
  if (!lines.length) {
    lines.push("See the success flag and the difference tier. Do not add a causal claim about the correction beyond those rules.");
  }
  return lines;
}

function resultMarkdown(lock, score) {
  const s = score.summaries;
  const lines = [
    "# SINGLE-TRAJECTORY-1 result",
    "",
    `Status: ${score.verdict.code}.`,
    `Benefit verdict: ${score.verdict.benefit ? "yes" : "no"}.`,
    `Difference tier: ${score.verdict.tier}.`,
    "",
    "The test set was scored once under the locked manifest.",
    "Baseline proposal, baseline result, and their scripts were not modified.",
    "Bootstrap coverage is approximate.",
    "",
    "## Primary",
    "",
    `Corrected engine accuracy: ${rate(s.engine.correct, s.engine.total)}.`,
    `Corrected integrator accuracy: ${rate(s.integrator.correct, s.integrator.total)} at a=${lock.selected_integrator.a}, lambda=${lock.selected_integrator.lambda}.`,
    `Mean paired block difference, engine minus integrator: ${fmt(score.mean_difference)}.`,
    "",
    intervalLine("Difference", score.intervals.difference),
    intervalLine("Engine accuracy", score.intervals.engine),
    intervalLine("Integrator accuracy", score.intervals.integrator),
    "",
    "Primary success required both a difference lower bound above +0.05 and an engine lower bound above 0.50.",
    "",
    "## Diagnostics",
    "",
    "| representation | accuracy | 95 percent interval |",
    "| --- | --- | --- |",
    `| corrected engine | ${rate(s.engine.correct, s.engine.total)} | [${fmt(score.intervals.engine.low)}, ${fmt(score.intervals.engine.high)}] |`,
    `| raw final | ${rate(s.raw.correct, s.raw.total)} | [${fmt(score.intervals.raw.low)}, ${fmt(score.intervals.raw.high)}] |`,
    `| final minus start | ${rate(s.delta.correct, s.delta.total)} | [${fmt(score.intervals.delta.low)}, ${fmt(score.intervals.delta.high)}] |`,
    `| initial only | ${rate(s.initial.correct, s.initial.total)} | not bootstrapped; exact-half check |`,
    `| final input only | ${rate(s.final_input.correct, s.final_input.total)} | not bootstrapped; exact-half check |`,
    "",
    `Cue rule perfect: ${score.cue_rule_perfect ? "yes" : "no"}.`,
    `Leakage controls exactly half: ${score.leakage_exact_half ? "yes" : "no"}.`,
    "",
    "## Reading",
    "",
    ...readings(score),
    "",
    "This experiment does not test memory modules, basin projection, general intelligence, or the original four-generator classification claim.",
    "",
    "The limitation is deliberate. A positive result would show usable single-trajectory information on this temporal task. It would not turn the old paired contrast into a demonstrated capability.",
    "",
    "## Blocks",
    "",
    "Each value is accuracy across the four episodes of that seed.",
    "",
    "| seed | engine | integrator | difference | raw | delta |",
    "| ---: | ---: | ---: | ---: | ---: | ---: |",
  ];
  for (const block of score.blocks) {
    lines.push(`| ${block.seed} | ${fmt(block.engine)} | ${fmt(block.integrator)} | ${fmt(block.difference)} | ${fmt(block.raw)} | ${fmt(block.delta)} |`);
  }
  lines.push("");
  return lines.join("\n");
}

function runTest() {
  if (existsSync(path.join(root, RESULT_JSON))) fail("result already exists; refusing to score again");
  if (!existsSync(path.join(root, LOCK_JSON))) fail("missing lock");
  const lock = JSON.parse(readFileSync(path.join(root, LOCK_JSON), "utf8"));
  verifyLock(lock);
  const test = simulateSplit("test");
  assertSplit(test, "test");
  const scored = python("--score", { test: packEpisodes(test), lock });
  if (!scored.cue_rule_perfect || !scored.leakage_exact_half) {
    scored.verdict = { code: "INVALID_AFTER_EXPOSURE", benefit: false, tier: "NONE" };
  } else if (scored.summaries.integrator.accuracy > 0.85) {
    scored.verdict = { code: "UNEXPECTED_TEST_CEILING", benefit: false, tier: "NO_BENEFIT" };
  } else {
    const advantage = scored.intervals.difference.low > 0.05;
    const chance = scored.intervals.engine.low > 0.5;
    let tier = "INCONCLUSIVE";
    if (advantage) tier = "ADVANTAGE_SUPPORTED_SUBJECT_TO_CHANCE";
    else if (scored.intervals.difference.high < 0.05) tier = "ADVANTAGE_RULED_OUT";
    scored.verdict = { code: advantage && chance ? "SUCCESS" : "NO_BENEFIT", benefit: advantage && chance, tier };
  }
  scored.mean_difference = scored.blocks.reduce((sum, block) => sum + block.difference, 0) / scored.blocks.length;
  const result = {
    experiment: "SINGLE-TRAJECTORY-1",
    engine_reference: lock.engine_reference,
    lock_status: lock.status,
    selected_engine_lambda: lock.selected_engine.lambda,
    selected_integrator_a: lock.selected_integrator.a,
    selected_integrator_lambda: lock.selected_integrator.lambda,
    ...scored,
  };
  writeAtomic(RESULT_JSON, `${JSON.stringify(result, null, 2)}\n`);
  writeAtomic(RESULT_MD, resultMarkdown(lock, result));
  console.log(`test status ${result.verdict.code}`);
  console.log(`engine ${result.summaries.engine.correct}/${result.summaries.engine.total}`);
  console.log(`integrator ${result.summaries.integrator.correct}/${result.summaries.integrator.total}`);
  console.log(`difference ${fmt(result.mean_difference)} [${fmt(result.intervals.difference.low)}, ${fmt(result.intervals.difference.high)}]`);
}

const mode = process.argv[2];
if (mode === "parity") runParity();
else if (mode === "train-val") runTrainVal();
else if (mode === "test") runTest();
else fail("usage: parity | train-val | test");
